version: '3'
services:
  ##### Frontend Services #####
  user-frontend:
    image: stratumn/elk-js-user:latest
    ports:
      - '3001:80'
    environment:
      - PORT=80
      - USER_SVC=http://user-backend
      - ELASTIC_APM_SERVICE_NAME=user-frontend
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
  task-frontend:
    image: stratumn/elk-js-task:latest
    ports:
      - '3002:80'
    environment:
      - PORT=80
      - TASK_SVC=http://task-backend
      - ELASTIC_APM_SERVICE_NAME=task-frontend
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200

  ##### Backend Services #####
  user-backend:
    image: stratumn/elk-go-user:latest
    environment:
      - PORT=80
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - ELASTIC_APM_SERVICE_NAME=user-backend
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
  task-backend:
    image: stratumn/elk-go-task:latest
    environment:
      - PORT=80
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - ELASTIC_APM_SERVICE_NAME=task-backend
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200

  ##### Application Database #####
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
    labels:
      - co.elastic.logs/module=postgresql
      - co.elastic.logs/fileset=access
      - co.elastic.metrics/module=postgresql
    restart: always

  ##### Monitoring #####
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ./ops/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - '5601:5601'
    volumes:
      - ./ops/config/kibana/:/usr/share/kibana/config:ro
    depends_on:
      - elasticsearch
  # TODO: how will the docker beats work for containers on ECS?
  # And for Postgres instances managed by RDS?
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.4
    user: root
    volumes:
      - ./ops/config/beats/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    depends_on:
      - elasticsearch
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.5.4
    user: root
    volumes:
      - ./ops/config/beats/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:6.5.4
    user: root
    ports:
      - '8200:8200'
    volumes:
      - ./ops/config/apm/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    depends_on:
      - elasticsearch
